#ifndef INCLUDE_GOPRO_VERSION_H
#define INCLUDE_GOPRO_VERSION_H

#define LIBGOPRO_VERSION          "0.0.1"
#define LIBGOPRO_VERSION_MAJOR    0
#define LIBGOPRO_VERSION_MINOR    0
#define LIBGOPRO_VERSION_REVISION 1

#endif
